
exports.mainPage = function(d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>

    <head>
        <meta charset="UTF-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
        <title>Music Database</title>
    </head>

    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Music Database</h1>
            </header>
            <div class="w3-container">
                <p>Welcome to the Music Database. Here you can find information about composers and music periods.</p>
                <p>Choose one of the following options:</p>
                <ul>
                    <li><a href="/compositores">Composers</a></li>
                    <li><a href="/periodos">Periods</a></li>
                </ul>
            </div>
            <footer class="w3-container w3-teal">
                <h5>Generated by Diogo Araújo in ${d}</h5>
            </footer>
        </div>
    </body>
    </html>
    `
    return pagHTML
}
        

///// COMPOSER'S TEMPLATES ///////////////////////////////////////////////////////////////////////////////////////////
exports.composerListPage = function(slist, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Composer Management</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h1>Composer List
                    <a class="w3-btn w3-round w3-grey" href="/compositores/registo">+</a>
                    </h1>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th>
                            <th>Name</th>
                            <th>Period</th>
                        </tr>
                `
    
    for(let i=0; i < slist.length ; i++){
        pagHTML += `
                <tr>
                    <td>${slist[i].id}</td>
                    <td>
                        <a href="/compositores/${slist[i].id}">
                            ${slist[i].nome}
                        </a>
                    </td>
                    <td>${slist[i].periodo}</td>
                    <td>
                        [<a href="/compositores/edit/${slist[i].id}">Edit</a>][<a href="/compositores/delete/${slist[i].id}">Delete</a>]
                    </td>
                </tr>
        `
    }

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-teal">
                    <h5>Generated by Diogo Araújo in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

exports.composerFormPage = function(periods,d){
    periodValue = "Select Period"
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Composer Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-teal">
                    <h2>Composer Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        
                        <label>Id (Ex: C2345)</label>
                        <input class="w3-input w3-round" type="text" name="id" required/>
                        
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome" required/>
                        
                        <legend>Period</legend>
                        <select class="w3-select" name="periodo">
                        <option value="Undefined">${periodValue}</option>`

                    for(i=0; i < periods.length; i++){
                        pagHTML += `
                                    <option value="${periods[i].nome}">${periods[i].nome}</option>
                                `
                    }
                    
                    pagHTML += `
                        </select>
                        
                        <label>Biography</label>
                        <input class="w3-input w3-round" type="text" name="bio"/>
                        
                        <label>Birth date</label>
                        <input class="w3-input w3-round" type="date" name="dataNasc"/>
                        
                        <label>Death date</label>
                        <input class="w3-input w3-round" type="date" name="dataObito"/>
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-teal w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-teal">
                    <h5>Generated by Diogo Araújo in ${d} - [<a href="/compositores">Return</a>]</h5>
                </footer>
            
            </div>
    `

    return pagHTML
}

exports.composerFormEditPage = function(c, periods,d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Composer Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-teal">
                    <h2>Composer Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" readonly value="${c.id}"/>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome" value="${c.nome}"/>

                        <legend>Period</legend>
                        <select class="w3-select" name="periodo">
                        <option value="${c.periodo}">${c.periodo}</option>`

                    for(i=0; i < periods.length; i++){
                        if (periods[i].nome != c.periodo){
                            pagHTML += `
                                    <option value="${periods[i].nome}">${periods[i].nome}</option>
                                `
                        }
                    }
                    
                    pagHTML += `
                        </select>
                        

                        <label>Biography</label>
                        <input class="w3-input w3-round" type="text" name="biografia" value="${c.bio}"/>
                        <label>Birth date</label>
                        <input class="w3-input w3-round" type="date" name="nascimento" value="${c.dataNasc}"/>
                        <label>Death date</label>
                        <input class="w3-input w3-round" type="date" name="morte" value="${c.dataObito}"/>
                    </fieldset>
                    
                    <br/>
                    <button class="w3-btn w3-teal w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-teal">
                    <h5>Generated by Diogo Araújo in ${d} - [<a href="/compositores">Return</a>]</h5>
                </footer>
            
            </div>
    `
    return pagHTML
}

exports.composerPage = function( composer, d ){
    var pagHTML = `
    <html>
    <head>
        <title>Composer: ${composer.id}</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Composer ${composer.id}</h1>
            </header>

            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
                    <li><b>Name: </b> ${composer.nome}</li>
                    <li><b>Period: </b> ${composer.periodo}</li>
                    <li><b>Biography: </b> ${composer.bio}</li>
                    <li><b>Birth date: </b> ${composer.dataNasc}</li>
                    <li><b>Death date: </b> ${composer.dataObito}</li>
                </ul>
            </div>
            
            <footer class="w3-container w3-teal">
                <address>Generated by Diogo Araújo in ${d} - [<a href="/compositores">Return</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
    return pagHTML
}

///// PERIODS TEMPLATES ///////////////////////////////////////////////////////////////////////////////////////////
exports.periodListPage = function(slist, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Period Management</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h1>Period List
                    <a class="w3-btn w3-round w3-grey" href="/periodos/registo">+</a>
                    </h1>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th>
                            <th>Name</th>
                        </tr>
                `
    
    for(let i=0; i < slist.length ; i++){
        pagHTML += `
                <tr>
                    <td>${slist[i].id}</td>
                    <td>
                        <a href="/periodos/${slist[i].id}">
                            ${slist[i].nome}
                        </a>
                    </td>
                    <td>
                        [<a href="/periodos/edit/${slist[i].id}">Edit</a>][<a href="/periodos/delete/${slist[i].id}">Delete</a>]
                    </td>
                </tr>
        `
    }

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-teal">
                    <address>Generated by Diogo Araújo in ${d} - [<a href="/">Return</a>]</address>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

exports.periodFormPage = function(d){
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Period Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-teal">
                    <h2>Period Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id (Ex: P5)</label>
                        <input class="w3-input w3-round" type="text" name="id" required/>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome" required/>
                        <label>Description</label>
                        <input class="w3-input w3-round" type="text" name="desc" required/>
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-teal w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-teal">
                    <h5>Generated by Diogo Araújo in ${d} - [<a href="/periodos">Return</a>]</h5>
                </footer>
            
            </div>
    `
}

exports.periodFormEditPage = function(p, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Period Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-teal">
                    <h2>Period Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" readonly value="${p.id}"/>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome" value="${p.nome}"/>
                        <label>Description</label>
                        <input class="w3-input w3-round" type="text" name="desc" value="${p.desc}"/>
                    </fieldset>
                    
                    <br/>
                    <button class="w3-btn w3-teal w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-teal">
                    <h5>Generated by Diogo Araújo in ${d} - [<a href="/periodos">Return</a>]</h5>
                </footer>
            
            </div>
    `
    return pagHTML
}

exports.periodPage = function( period, d ){
    var pagHTML = `
    <html>
    <head>
        <title>Period: ${period.id}</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Period ${period.id}</h1>
            </header>

            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
                    <li><b>Name: </b> ${period.nome}</li>
                    <li><b>Description: </b> ${period.desc}</li>
                </ul>
            </div>
            
            <footer class="w3-container w3-teal">
                <address>Generated by Diogo Araújo in ${d} - [<a href="/periodos">Return</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
    return pagHTML
}

/////// Error Treatment ///////////////////////////////////////////////////////////////////////////////////////////
exports.errorPage = function(errorMessage, d){
    return `
    <p>${d}: Error: ${errorMessage}</p>
    `
}