
///// COMPOSER'S TEMPLATES ///////////////////////////////////////////////////////////////////////////////////////////
exports.composerListPage = function(slist, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Composer Management</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h1>Composer List
                    <a class="w3-btn w3-round w3-grey" href="/compositores/registo">+</a>
                    </h1>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th>
                            <th>Name</th>
                            <th>Período</th>
                        </tr>
                `
    
    for(let i=0; i < slist.length ; i++){
        pagHTML += `
                <tr>
                    <td>${slist[i].id}</td>
                    <td>
                        <a href="/compositores/${slist[i].id}">
                            ${slist[i].nome}
                        </a>
                    </td>
                    <td>${slist[i].periodo}</td>
                    <td>
                        [<a href="/compositores/edit/${slist[i].id}">Edit</a>][<a href="/compositores/delete/${slist[i].id}">Delete</a>]
                    </td>
                </tr>
        `
    }

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by Diogo Araújo in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

exports.composerFormPage = function(d){
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Composer Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Composer Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" required/>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome" required/>
                        <label>Period</label>
                        <input class="w3-input w3-round" type="text" name="periodo" required/>
                        <label>Biography</label>
                        <input class="w3-input w3-round" type="text" name="biografia"/>
                        <label>Birth date</label>
                        <input class="w3-input w3-round" type="date" name="nascimento"/>
                        <label>Death date</label>
                        <input class="w3-input w3-round" type="date" name="morte"/>
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by Diogo Araújo in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            
            </div>
    `
}

exports.composerFormEditPage = function(c, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Composer Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Composer Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" readonly value="${c.id}"/>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome" value="${c.nome}"/>
                        <label>Period</label>
                        <input class="w3-input w3-round" type="text" name="periodo" value="${c.periodo}"/>
                        <label>Biography</label>
                        <input class="w3-input w3-round" type="text" name="biografia" value="${c.bio}"/>
                        <label>Birth date</label>
                        <input class="w3-input w3-round" type="date" name="nascimento" value="${c.dataNasc}"/>
                        <label>Death date</label>
                        <input class="w3-input w3-round" type="date" name="morte" value="${c.dataObito}"/>
                    </fieldset>
                    
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by Diogo Araújo in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            
            </div>
    `
    return pagHTML
}

// ---------------Composer's Page--------------------------------
exports.composerPage = function( composer, d ){
    var pagHTML = `
    <html>
    <head>
        <title>Composer: ${composer.id}</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Composer ${composer.id}</h1>
            </header>

            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
                    <li><b>Name: </b> ${composer.nome}</li>
                    <li><b>Period: </b> ${composer.period}</li>
                    <li><b>Biography: </b> ${composer.bio}</li>
                    <li><b>Birth date: </b> ${composer.dataNasc}</li>
                    <li><b>Death date: </b> ${composer.dataObito}</li>
                </ul>
            </div>
            
            <footer class="w3-container w3-teal">
                <address>Gerado por Diogo Araújo em ${d} - [<a href="/">Voltar</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
    return pagHTML
}

///// PERIODS TEMPLATES ///////////////////////////////////////////////////////////////////////////////////////////


// -------------- Error Treatment ------------------------------
exports.errorPage = function(errorMessage, d){
    return `
    <p>${d}: Error: ${errorMessage}</p>
    `
}